### ISSUE TITLE
WebView2 for .NET GA and Fixed Version GA

### ISSUE THREAD

**Issue by pagoe-msft** [MicrosoftEdge/WebView2Announcements#10]
## WebView2 for .NET GA and Fixed Version GA

Today, we are thrilled to announce that Microsoft Edge WebView2 is generally available for production .NET Framework, .NET Core, and .NET 5 applications. Furthermore, the Fixed Version distribution mode is also generally available for production applications!

See our [official announcement](https://devblogs.microsoft.com/dotnet/announcing-general-availability-for-microsoft-edge-webview2-for-net-and-fixed-distribution-method/) for more details.

Checkout:
- Forward compatible SDK: [Release Notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes) | [NuGet Download](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.664.37)
- Fixed Version WebView2 Runtime: [Documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode) | [Download](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)

Please download and try these out. Use the [WebView2Feedback repo](https://github.com/MicrosoftEdge/WebView2Feedback) to report any bugs or issues you find. Thanks!

**Comment by ivoloshin** [comment]
Does this include implementation of CookieManager? I'm still using `1.0.674-prerelease` SDK which requires Edge Canary.

**Comment by Symbai** [comment]
According to the linked changelog it does not: https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes

**Comment by rgup63** [comment]
I see a blank window if I try to host WebView2 in a sample VSIX extension with 1.0.664.37 GA release. Does this GA release not support it?  Same use case was working with 1.0.674 pre-release. Does it mean all the fixes are not included in this GA build?

**Comment by kirsan31** [comment]
> Does it mean all the fixes are not included in this GA build?

I think that 1.0.**664.37** defiantly < 1.0.**674**, so sadly but more NO then yes :(
