### ISSUE TITLE
SDK Release: 1.0.721-prerelease

### ISSUE THREAD

**Issue by pagoe-msft** [MicrosoftEdge/WebView2Announcements#12]
## New SDK Released!

Today, we released the 1.0721 pre-release package. The previous pre-release package was removed due to a critical bug that has now been resolved with this release.

### [NuGet Download](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.721-prerelease)

Please download and try it out! Use the WebView2Feedback repo to report any bugs or issues you find. Thanks!

**Comment by rgup63** [comment]
Any idea on release dates for `1.0.674 GA` and `1.0.721 GA ` ?

**Comment by peiche-jessica** [comment]
@rgup63 Though we won't be releasing `1.0.674 GA` and `1.0.721 GA`, the experimental APIs in 1.0.674-prerelease and 1.0.721-prelease may be promoted in future release packages. Please checkout our latest 1.0.705.50 release package (#15). Thanks!
