### ISSUE TITLE
API Review: BackgroundColor

### ISSUE THREAD

**Issue by johna-ms** [MicrosoftEdge/WebView2Announcements#13]
# API Review

## Title: BackgroundColor
This API lets developers set the background color for a WebView. The background color is the color that shows when no web content is showing. This means a developer can set the color that shows before the first navigation, in between navigations before the next page is rendered, and for pages that have no css background style properties set. Developers can replace the 'white flash' between loading pages with a color better suited to their application. For websites with no specified background color, developers can display web contents over a color of their choosing. They can also do away with the background color entirely with transparency and have the 'in between pages color' just be hosting content, or have hosting app content be the backdrop for webpages without a background color specified.

## API Spec: https://github.com/MicrosoftEdge/WebView2Feedback/pull/809

Please review the pull request and add any feedback you have about this API. We appreciate your input and support!

**Comment by johna-ms** [comment]
Closing this until we've received preliminary feedback.

**Comment by jschroedl** [comment]
This looks like a good start.
