### ISSUE TITLE
DevTools Protocol Extension (Preview) Release: 1.0.824

### ISSUE THREAD

**Issue by pagoe-msft** [MicrosoftEdge/WebView2Announcements#20]
## Preview Release of DevTools ProtocolExtension
The Microsoft Edge WebView2 team has released the preview version of the DevTools Protocol Extension. This package allows .NET developers to directly call [Chromium DevTools Protocol APIs](https://chromedevtools.github.io/devtools-protocol/) within their WebView2 applications. Checkout [this guide](https://docs.microsoft.com/microsoft-edge/webview2/howto/chromium-devtools-protocol) to learn more about how to get started.

### [NuGet Download](https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension/)

Please download and try out the new SDK release. Use the WebView2Feedback repo to report any bugs or issues you find. Thanks!

**Comment by lsim** [comment]
Just a heads up: This package needs a refresh. It depends on a vulnerable `System.Text.Encodings.Web` version

See https://osv.dev/vulnerability/GHSA-ghhp-997w-qr28

**Comment by Danielx64** [comment]
> Just a heads up: This package needs a refresh. It depends on a vulnerable `System.Text.Encodings.Web` version
> 
> See https://osv.dev/vulnerability/GHSA-ghhp-997w-qr28
> 

I would also post that in the other GitHub for webview2 so that it gets more exposure

**Comment by lsim** [comment]
Thanks for the input but would you mind posting a link? It's not obvious to me which repo you're referring to. :)

**Comment by Danielx64** [comment]
> Thanks for the input but would you mind posting a link? It's not obvious to me which repo you're referring to. :)

Sorry, here it is: https://github.com/MicrosoftEdge/WebView2Feedback
