### ISSUE TITLE
Webview 2 content is getting clipped partially and doesn't resize properly to it's content height

### ISSUE THREAD

**Issue by ranaprathap2** [MicrosoftEdge/WebView2Announcements#22]
![image](https://user-images.githubusercontent.com/35987175/116775306-00bf3980-aa80-11eb-85af-1cffce57e9b9.png)

**Comment by ranaprathap2** [comment]
I want to disable the WebView2's vertical scrolling and to keep the parent element scrolling instead. So I tried to resize the webview2's height to the height of its actually rendered content.

What I observed is the Webview2's height is getting set properly to its contents height, But despite still the height being set properly the content is not getting rendered fully, Instead only the partial content at the top is shown.

**Comment by ilsubyeega** [comment]
Please, this is not a bug or feature request page, look at the readme. https://github.com/MicrosoftEdge/WebView2Announcements/blob/master/README.md

**Comment by ranaprathap2** [comment]
Will close and move this to Feedback repo, Thanks @ilsubyeega .
