### ISSUE TITLE
New feature notification for User Directory Folder, potential breaking change

### ISSUE THREAD

**Issue by DavidShoe** [MicrosoftEdge/WebView2Announcements#26]
There is a new upcoming feature notice at: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1410

The default handling for the UDF if the developer doesn't specify where to put it will be changing, the feedback item has more details.  This is upcoming work we wanted to inform the developer community about.

**Comment by jschroedl** [comment]
Excellent, I think the change is a good one.
