### ISSUE TITLE
API Review: ServerCertificateErrorDetected

### ISSUE THREAD

**Issue by monica-ch** [MicrosoftEdge/WebView2Announcements#39]
# API Review

## Title: ServerCertificateErrorDetected
This is a new API which provides an option to trust the server's TLS certificate at the application level and render the page without prompting the user about the TLS error or can cancel the request.

## API Spec: https://github.com/MicrosoftEdge/WebView2Feedback/pull/2179

Please review the pull request and add any feedback you have about this API. We appreciate your input and support!

**Comment by ajtruckle** [comment]
I don’t know how to review these apis you make. I don’t personally download pull requests or anything and raw md files are complicated to read. Can’t I read a word file or html file?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: monica-ch ***@***.***>
Sent: Tuesday, March 1, 2022 4:44:19 PM
To: MicrosoftEdge/WebView2Announcements ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftEdge/WebView2Announcements] API Review: ServerCertificateErrorDetected (Issue #39)


API Review
Title: ServerCertificateErrorDetected

This is a new API which provides an option to trust the server's TLS certificate at the application level and render the page without prompting the user about the TLS error or can cancel the request.

API Spec: MicrosoftEdge/WebView2Feedback#2179<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftEdge%2FWebView2Feedback%2Fpull%2F2179&data=04%7C01%7C%7C69d8b930a4bb49351b0908d9fba2bbe0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637817498615382280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AEfyTbtZmkpt4mOs6zcUyB0%2BY9%2BZXbLq5VwuXQj9ZGo%3D&reserved=0>

Please review the pull request and add any feedback you have about this API. We appreciate your input and support!
