### ISSUE TITLE
Documentation: New Conceptual Documentation for WebView2

### ISSUE THREAD

**Issue by nishitha-burman** [MicrosoftEdge/WebView2Announcements#41]
We have updated our WebView2 documentation with a brand new table of contents to make it easier to find the content you need, and added the following docs to better explain new or complex content!

- [Interop of native-side and web-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/communicate-btwn-web-native)
- [Call web-side code from native-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript)
- [Call native-side code from web-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/hostobject)
- [Clear browsing data from the user data folder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/clear-browsing-data?tabs=csharp)
- [Basic authentication for WebView2 apps](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/basic-authentication?tabs=csharp)
- [Customize context menus in WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus?tabs=csharp)

**Comment by ajtruckle** [comment]
Thanks! Does this mean that the context menu feature is now out of beta and available in the stable NuGet package?

**Comment by jarno9981** [comment]
@nishitha-burman password clearing does not work autofill data and password still usabele after clearing
