### ISSUE TITLE
API Review: User Agent

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Announcements#9]
# API Review

## Title: User Agent
This is a new API for modifying WebView2's User Agent String.

## API Spec: https://github.com/MicrosoftEdge/WebView2Feedback/pull/631

Please review the pull request and add any feedback you have about this API. We appreciate your input and support!

**Comment by shawty** [comment]
Hi jason, is there an actual link to the doc to read?  All I can seem to find are git-diff logs.

**Comment by champnic** [comment]
The spec doc is the file being changed. Here's a direct link to it:
https://github.com/MicrosoftEdge/WebView2Feedback/pull/631/files?short_path=cf4dc9b#diff-cf4dc9b4d24b8c3fd6e51738eddff641d65b9a5c438980c271808ddb40cde60f
